set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

call vundle#end()

nmap <F3> :set invrelativenumber<CR>
nmap <F4> :set invnumber<CR>
