#!/usr/bin/env bash
{% if yadm.os == "Darwin" %}
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
{% endif %}
{% if yadm.os == "Linux" %}
export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"
{% endif %}
exec /usr/bin/ssh-keygen "$@"