#!/bin/sh

set -e
syslog -s -l warn "Set environment variables with ~/.config/environment $(whoami) - start"

launchctl setenv XSH_CONFIG_DIR ~/.config/shell
launchctl setenv GNUPGHOME ~/.config/gnupg
launchctl setenv SSH_AUTH_SOCK $(gpgconf --list-dirs agent-ssh-socket)
syslog -s -l warn "Set environment variables with ~/.config/environment $(whoami) - complete"
